/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.su23.dynamic.property.catalog

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
